-- In-body blog illustrations generated by the BFL pipeline. Stored as
-- separate rows (one per image) rather than a JSON column on BlogPost so
-- each image is served through its own cached /api/blog/image/[id] route
-- and the page HTML stays small.
CREATE TABLE "BlogPostImage" (
    "id" TEXT NOT NULL,
    "postId" TEXT NOT NULL,
    "idx" INTEGER NOT NULL,
    "dataUrl" TEXT NOT NULL,
    "alt" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "BlogPostImage_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "BlogPostImage_postId_idx_key" ON "BlogPostImage"("postId", "idx");

CREATE INDEX "BlogPostImage_postId_idx" ON "BlogPostImage"("postId");

ALTER TABLE "BlogPostImage"
    ADD CONSTRAINT "BlogPostImage_postId_fkey"
    FOREIGN KEY ("postId") REFERENCES "BlogPost"("id")
    ON DELETE CASCADE ON UPDATE CASCADE;
