-- Add monthly ElevenLabs character usage tracking to User
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "ttsCharsUsedThisMonth" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "ttsCharsResetAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
